---
- name: validate required connection is configured
  fail:
    msg: "expected connection value to be set to network_cli, got {{ ansible_connection }}"
  when: ansible_connection != 'network_cli'

- name: collect platform capabilities as facts
  nxos_capabilities:

- name: load command variables
  include_vars:
    name: commands
    file: get_facts.yaml

- name: run command and parse output
  include_tasks: run_cli.yaml
  vars:
    nxos_command: "{{ item.value.command }}"
    nxos_parser: "{{ item.value.parser }}"
  loop: "{{ lookup('dict', commands) }}"
  when: item.key in subset | default(item.key) or subset in ['*', 'all']
